const express=require('express');const http=require('http');const{Server}=require('socket.io');const path=require('path');const fs=require('fs');
const app=express(),server=http.createServer(app),io=new Server(server);app.get('/health',(_,r)=>r.send('ok'));app.get('/board.jpg',(_,r)=>{try{const b64=fs.readFileSync(path.join(__dirname,'public','assets','board-restored-hq.jpg'),'utf8').trim();r.set('Content-Type','image/jpeg');r.set('Cache-Control','public, max-age=86400');r.send(Buffer.from(b64,'base64'))}catch(e){r.status(500).send('Board image unavailable')}});app.use(express.static(path.join(__dirname,'public')));
const rooms=new Map(),CH='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',COL=['#dc3545','#0d6efd','#198754','#fd7e14','#6f42c1','#20c997'];
const code=()=>{let s='';for(let i=0;i<5;i++)s+=CH[Math.floor(Math.random()*CH.length)];return rooms.has(s)?code():s};const name=v=>String(v||'').trim().slice(0,20)||'Player';
const pub=r=>({code:r.code,phase:r.phase,turnIndex:r.turnIndex,winnerId:r.winnerId,lastEvent:r.lastEvent,players:r.players.map(({socketId,...p})=>p)});const cur=r=>r.players[r.turnIndex];const emit=r=>io.to(r.code).emit('state',pub(r));
function next(r){if(!r.players.length||r.phase!=='playing')return;r.turnIndex=(r.turnIndex+1)%r.players.length;const p=cur(r);if(p&&p.skipTurns>0){p.skipTurns--;r.lastEvent=`${p.name} misses this turn.`;setTimeout(()=>{if(r.phase==='playing'&&cur(r)?.id===p.id){next(r);emit(r)}},900)}}
function rule(p,n){if(p==='start'||p===5)return{d:Math.min(19,(p==='start'?0:p)+n)};switch(p){case 1:return{d:n%2?'start':7};case 2:return n%2?{skip:1}:{d:14};case 3:return{d:n>2?7:'start'};case 4:return{d:n===6?19:6};case 6:return{d:n<4?17:11};case 7:return{d:n%2?10:12};case 8:return{d:n%2?5:13};case 9:return n>3?{d:10}:{skip:1};case 10:return{d:13};case 11:return{d:'start'};case 12:return{d:9};case 13:return{d:n>4?19:15};case 14:return{d:n===6?19:9};case 15:return{d:n%2?8:7};case 16:return{d:n>=5?19:11};case 17:return{d:n===6?18:'start'};case 18:return{d:n===1?19:12};case 19:return{win:true};default:return{d:p}}}
function resolve(r,p,n){const from=p.position,x=rule(from,n);if(x.win){r.phase='finished';r.winnerId=p.id;return}if(x.skip){p.skipTurns+=x.skip;r.lastEvent=`${p.name} must miss a turn.`;next(r);return}p.position=x.d;r.lastEvent=n?`${p.name} rolled ${n} and moves from ${from==='start'?'Start':'square '+from} to ${x.d==='start'?'Start':'square '+x.d}.`:`${p.name} follows the instruction and moves to ${x.d==='start'?'Start':'square '+x.d}.`;if(x.d===19){r.phase='finished';r.winnerId=p.id;r.lastEvent=`${p.name} reaches square 19 - Manumissio!`}else next(r)}
io.on('connection',s=>{s.on('createRoom',({name:n},cb=()=>{})=>{const c=code(),id=Math.random().toString(36).slice(2,10),r={code:c,phase:'lobby',turnIndex:0,winnerId:null,lastEvent:'Room created.',players:[{id,socketId:s.id,name:name(n),position:'start',skipTurns:0,colour:COL[0],host:true}]};rooms.set(c,r);s.join(c);s.data.roomCode=c;s.data.playerId=id;cb({ok:true,roomCode:c,playerId:id});emit(r)});s.on('joinRoom',({roomCode:c,name:n},cb=()=>{})=>{c=String(c||'').toUpperCase();const r=rooms.get(c);if(!r)return cb({ok:false,error:'Room not found.'});if(r.phase!=='lobby')return cb({ok:false,error:'This game has already started.'});if(r.players.length>=6)return cb({ok:false,error:'This room is full.'});const id=Math.random().toString(36).slice(2,10);r.players.push({id,socketId:s.id,name:name(n),position:'start',skipTurns:0,colour:COL[r.players.length],host:false});s.join(c);s.data.roomCode=c;s.data.playerId=id;cb({ok:true,roomCode:c,playerId:id});emit(r)});s.on('startGame',()=>{const r=rooms.get(s.data.roomCode),p=r?.players.find(x=>x.id===s.data.playerId);if(!p?.host||r.phase!=='lobby')return;r.phase='playing';r.turnIndex=0;r.lastEvent=`${r.players[0].name} goes first.`;emit(r)});s.on('roll',()=>{const r=rooms.get(s.data.roomCode),p=r&&cur(r);if(!p||r.phase!=='playing'||p.id!==s.data.playerId||p.skipTurns>0)return;const n=Math.floor(Math.random()*6)+1;resolve(r,p,n);emit(r);io.to(r.code).emit('rolled',{playerId:p.id,roll:n})});s.on('resolveAutomatic',()=>{const r=rooms.get(s.data.roomCode),p=r&&cur(r);if(!p||p.id!==s.data.playerId||![10,11,12].includes(p.position))return;resolve(r,p,0);emit(r)});s.on('disconnect',()=>{const r=rooms.get(s.data.roomCode);if(!r)return;const i=r.players.findIndex(p=>p.id===s.data.playerId);if(i<0)return;const h=r.players[i].host;r.players.splice(i,1);if(!r.players.length)return rooms.delete(r.code);if(h)r.players[0].host=true;if(r.turnIndex>=r.players.length)r.turnIndex=0;r.lastEvent='A player disconnected.';emit(r)})});
server.listen(process.env.PORT||3000,()=>console.log('MONOPOLY BC online'));